### ISSUE TITLE
Euclid's Algorithm

### ISSUE THREAD

**Issue by prafulla-k-roy** [prafulla-k-roy/algo-education#10]
Write an implementation of Euclid's algorithm on an integer array with proper explanation through comments.

**Comment by Amn04** [comment]
Hi @prafulla-k-roy CA you please assign this to me I will do it using c++.

**Comment by harkar20** [comment]
Hi @prafulla-k-roy CA you please assign this to me I will do it using python

**Comment by Amn04** [comment]
Please close this issue as it is completed

**Comment by Amn04** [comment]
@prafulla-k-roy I am adding the python code as I  see the other guy is not doing it.
