### ISSUE TITLE
Linear Search Algorithm

### ISSUE THREAD

**Issue by prafulla-k-roy** [prafulla-k-roy/algo-education#2]
Write an implementation of linear search algorithm on an integer array with proper explanation through comments.

**Comment by SubhashThenua** [comment]
@prafulla-k-roy Can you please assign this to me?

Thanks!

**Comment by utkr07** [comment]
I wud request you to please assign this to me. Thank you so much. @prafulla-k-roy

**Comment by Ashpreetwadhwa** [comment]
Hey @prafulla-k-roy I can do this in c++,java,python
