### ISSUE TITLE
Bubble Sort Algorithm

### ISSUE THREAD

**Issue by prafulla-k-roy** [prafulla-k-roy/algo-education#4]
Write an implementation of bubble sort algorithm on an integer array with proper explanation through comments.

**Comment by JoaoDanielRufino** [comment]
Hi, can I work on this ?

**Comment by tanishqvashisht** [comment]
I can do this in java @prafulla-k-roy can you assign this to me in java

**Comment by PrakritiRaw** [comment]
Hey @prafulla-k-roy can you please assign this to me.
I can work on this in python, cpp and java.
