### ISSUE TITLE
Selection Sort Algorithm

### ISSUE THREAD

**Issue by prafulla-k-roy** [prafulla-k-roy/algo-education#5]
Write an implementation of selection sort algorithm on an integer array with proper explanation through comments.

**Comment by SubhashThenua** [comment]
@prafulla-k-roy  Can i work on this?

Thanks!

**Comment by tanishqvashisht** [comment]
I can do this in java @prafulla-k-roy , can you assign this to me in java

**Comment by jayeshs08** [comment]
hello @prafulla-k-roy kindly assign this to me. I would love to write this code in cpp or java!!

**Comment by prafulla-k-roy** [comment]
Please perform it in C++ and Python. I have already received submission for Java.

**Comment by Ashpreetwadhwa** [comment]
hey @prafulla-k-roy i can do it in c++ and python

**Comment by vansh-patel-8123** [comment]
I want to contribute , please assign me
