### ISSUE TITLE
Insertion Sort Algorithm

### ISSUE THREAD

**Issue by prafulla-k-roy** [prafulla-k-roy/algo-education#6]
Write an implementation of insertion sort algorithm on an integer array with proper explanation through comments.

**Comment by SubhashThenua** [comment]
@prafulla-k-roy Can you please assign this to me?

Thanks!

**Comment by tanishqvashisht** [comment]
I can do this in java @prafulla-k-roy can you assign this to me

**Comment by PrakritiRaw** [comment]
hey @prafulla-k-roy , I can implement this is C++, and would love to do this.

**Comment by PrakritiRaw** [comment]
Hii... kindly assign this to me . I can implement this in CPP.

**Comment by prafulla-k-roy** [comment]
Mission Accomplished Everyone!!!
