### ISSUE TITLE
Merge Sort Algorithm

### ISSUE THREAD

**Issue by prafulla-k-roy** [prafulla-k-roy/algo-education#8]
Write an implementation of merge sort algorithm on an integer array with proper explanation through comments.

**Comment by sunidhisachan** [comment]
hey @prafulla-k-roy I can do this , please assign this to me.

**Comment by tanishqvashisht** [comment]
I can do this in java @prafulla-k-roy , can you assign this to me for java

**Comment by jayeshs08** [comment]
hello @prafulla-k-roy kindly assign this to me. I would love to write this code in cpp or java !!

**Comment by utkr07** [comment]
Can you please assign this to me? I'll provide a good solution for this program.
