### ISSUE TITLE
Counting Sort Algorithm

### ISSUE THREAD

**Issue by prafulla-k-roy** [prafulla-k-roy/algo-education#9]
Write an implementation of counting sort algorithm on an integer array with proper explanation through comments.

**Comment by JoaoDanielRufino** [comment]
Hi, can I work on this ?

**Comment by jayeshs08** [comment]
hello @prafulla-k-roy kindly assign this to me. I would love to write this code, as counting sort is one of my favourite sorting algorithm !!

**Comment by utkr07** [comment]
Can you please assign this to me? I'll provide an efficient solution for this sorting method.
